import { Component, OnInit } from '@angular/core';
import { MatDialog } from '@angular/material/dialog';

@Component({
  selector: 'app-transport-workers-dashboard',
  templateUrl: './transport-workers-dashboard.component.html',
  styleUrl: './transport-workers-dashboard.component.css',
})
export class TransportWorkersDashboardComponent implements OnInit {
  constructor(public dialog: MatDialog) {}
  workers = [
    {
      name: 'Mavin Dee',
      email: 'mavindee@gmail.com',
      category: 'Bus',
      carType: 'Toyota',
      plateNumber: 'DKA-234-uy',
      address: 'NO 12 teen street Abuja, Nigeria',
      carPark: 'Peace Park',
      image: 'assets/images/adela.svg',
      selected: false,
    },
    {
      name: 'Dapious Kodewarlock',
      email: 'kodewarlock@gmail.com',
      category: 'Car',
      carType: 'Toyota',
      plateNumber: 'DKA-234-uy',
      address: 'NO 12 teen street Abuja, Nigeria',
      carPark: 'Peace Park',
      image: 'assets/images/jason.svg',
      selected: false,
    },
    {
      name: 'Mavin Dee',
      email: 'mavindee@gmail.com',
      category: 'Napep',
      carType: 'Toyota',
      plateNumber: 'DKA-234-uy',
      address: 'NO 12 teen street Abuja, Nigeria',
      carPark: 'Peace Park',
      image: 'assets/images/christian.svg',
      selected: false,
    },
    {
      name: 'Mavin Dee',
      email: 'mavindee@gmail.com',
      category: 'Bus',
      carType: 'Toyota',
      plateNumber: 'DKA-234-uy',
      address: 'NO 12 teen street Abuja, Nigeria',
      carPark: 'Peace Park',
      image: 'assets/images/adela.svg',
      selected: false,
    },
    {
      name: 'Mavin Dee',
      email: 'mavindee@gmail.com',
      category: 'Bus',
      carType: 'Toyota',
      plateNumber: 'DKA-234-uy',
      address: 'NO 12 teen street Abuja, Nigeria',
      carPark: 'Peace Park',
      image: 'assets/images/adela.svg',
      selected: false,
    },
    {
      name: 'Mavin Dee',
      email: 'mavindee@gmail.com',
      category: 'Bus',
      carType: 'Toyota',
      plateNumber: 'DKA-234-uy',
      address: 'NO 12 teen street Abuja, Nigeria',
      carPark: 'Peace Park',
      image: 'assets/images/jason.svg',
      selected: false,
    },
    {
      name: 'Mavin Dee',
      email: 'mavindee@gmail.com',
      category: 'Bus',
      carType: 'Toyota',
      plateNumber: 'DKA-234-uy',
      address: 'NO 12 teen street Abuja, Nigeria',
      carPark: 'Peace Park',
      image: 'assets/images/jason.svg',
      selected: false,
    },
    {
      name: 'Mavin Dee',
      email: 'mavindee@gmail.com',
      category: 'Bus',
      carType: 'Toyota',
      plateNumber: 'DKA-234-uy',
      address: 'NO 12 teen street Abuja, Nigeria',
      carPark: 'Peace Park',
      image: 'assets/images/christian.svg',
      selected: false,
    },
    {
      name: 'Mavin Dee',
      email: 'mavindee@gmail.com',
      category: 'Bus',
      carType: 'Toyota',
      plateNumber: 'DKA-234-uy',
      address: 'NO 12 teen street Abuja, Nigeria',
      carPark: 'Peace Park',
      image: 'assets/images/christian.svg',
      selected: false,
    },
    {
      name: 'Mavin Dee',
      email: 'mavindee@gmail.com',
      category: 'Bus',
      carType: 'Toyota',
      plateNumber: 'DKA-234-uy',
      address: 'NO 12 teen street Abuja, Nigeria',
      carPark: 'Peace Park',
      image: 'assets/images/christian.svg',
      selected: false,
    },
    {
      name: 'Mavin Dee',
      email: 'mavindee@gmail.com',
      category: 'Bus',
      carType: 'Toyota',
      plateNumber: 'DKA-234-uy',
      address: 'NO 12 teen street Abuja, Nigeria',
      carPark: 'Peace Park',
      image: 'assets/images/christian.svg',
      selected: false,
    },
    {
      name: 'Mavin Dee',
      email: 'mavindee@gmail.com',
      category: 'Bus',
      carType: 'Toyota',
      plateNumber: 'DKA-234-uy',
      address: 'NO 12 teen street Abuja, Nigeria',
      carPark: 'Peace Park',
      image: 'assets/images/christian.svg',
      selected: false,
    },
    {
      name: 'Mavin Dee',
      email: 'mavindee@gmail.com',
      category: 'Bus',
      carType: 'Toyota',
      plateNumber: 'DKA-234-uy',
      address: 'NO 12 teen street Abuja, Nigeria',
      carPark: 'Peace Park',
      image: 'assets/images/christian.svg',
      selected: false,
    },
    {
      name: 'Mavin Dee',
      email: 'mavindee@gmail.com',
      category: 'Bus',
      carType: 'Toyota',
      plateNumber: 'DKA-234-uy',
      address: 'NO 12 teen street Abuja, Nigeria',
      carPark: 'Peace Park',
      image: 'assets/images/christian.svg',
      selected: false,
    },
  ];
  closeModal() {
    this.dialog.closeAll();
  }
  ngOnInit(): void {}
}
